import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

dotenv.config({ path: path.join(__dirname, '../.env') });

const supabaseUrl = process.env.VITE_SUPABASE_URL;
const supabaseKey = process.env.VITE_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseKey) {
  console.error('❌ Missing VITE_SUPABASE_URL or VITE_SUPABASE_ANON_KEY in .env file!');
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey);

const today = new Date().toISOString().split('T')[0];
const now = new Date().toISOString();

const DECKS_TO_SEED = [
  { id: 'deck-family', user_id: 'user-teacher-1', author_name: 'VocaFast AI', title: 'Gia đình & Mối quan hệ', description: 'Từ vựng chủ đề gia đình, người thân, ông bà và mối quan hệ huyết thống.', category: 'people_feelings', icon: 'Users', color: 'from-pink-500 to-rose-600', is_custom: false, is_public: true, created_at: now, updated_at: now },
  { id: 'deck-personality', user_id: 'user-teacher-1', author_name: 'VocaFast AI', title: 'Tính cách & Phẩm chất', description: 'Từ vựng miêu tả tính cách, thái độ và phẩm chất cá nhân con người.', category: 'people_feelings', icon: 'Smile', color: 'from-purple-500 to-indigo-600', is_custom: false, is_public: true, created_at: now, updated_at: now },
  { id: 'deck-emotions', user_id: 'user-teacher-1', author_name: 'VocaFast AI', title: 'Cảm xúc & Tâm trạng', description: 'Từ vựng bộc lộ trạng thái cảm xúc, tâm trạng và thái độ con người.', category: 'people_feelings', icon: 'Heart', color: 'from-rose-500 to-pink-600', is_custom: false, is_public: true, created_at: now, updated_at: now },
  { id: 'deck-describing-people', user_id: 'user-teacher-1', author_name: 'VocaFast AI', title: 'Miêu tả Ngoại hình', description: 'Từ vựng miêu tả vóc dáng, diện mạo và đặc điểm bên ngoài con người.', category: 'people_feelings', icon: 'UserCheck', color: 'from-fuchsia-500 to-purple-600', is_custom: false, is_public: true, created_at: now, updated_at: now },
  { id: 'deck-body-actions', user_id: 'user-teacher-1', author_name: 'VocaFast AI', title: 'Hành động Cơ thể', description: 'Cử chỉ, cử động và cử chỉ điệu bộ trên cơ thể con người.', category: 'people_feelings', icon: 'Activity', color: 'from-red-500 to-rose-600', is_custom: false, is_public: true, created_at: now, updated_at: now },
  { id: 'deck-vegetables', user_id: 'user-teacher-1', author_name: 'VocaFast AI', title: 'Rau củ & Nông sản', description: 'Các loại rau củ, củ quả và nông sản dinh dưỡng hàng ngày.', category: 'food_dining', icon: 'Leaf', color: 'from-emerald-500 to-green-600', is_custom: false, is_public: true, created_at: now, updated_at: now },
  { id: 'deck-food-dishes', user_id: 'user-teacher-1', author_name: 'VocaFast AI', title: 'Món ăn & Ẩm thực', description: 'Từ vựng về các món ăn thông dụng, khai vị, món chính và đặc sản.', category: 'food_dining', icon: 'Utensils', color: 'from-amber-500 to-orange-600', is_custom: false, is_public: true, created_at: now, updated_at: now },
  { id: 'deck-fruits', user_id: 'user-teacher-1', author_name: 'VocaFast AI', title: 'Trái cây & Hoa quả', description: 'Tên gọi các loại trái cây tươi ngon, nhiệt đới và ôn đới.', category: 'food_dining', icon: 'Apple', color: 'from-red-500 to-amber-600', is_custom: false, is_public: true, created_at: now, updated_at: now },
  { id: 'deck-kitchenware', user_id: 'user-teacher-1', author_name: 'VocaFast AI', title: 'Nhà bếp & Dụng cụ nấu ăn', description: 'Các vật dụng, thiết bị nấu nướng và đồ dùng phòng bếp.', category: 'food_dining', icon: 'ChefHat', color: 'from-orange-500 to-yellow-600', is_custom: false, is_public: true, created_at: now, updated_at: now },
  { id: 'deck-beverages', user_id: 'user-teacher-1', author_name: 'VocaFast AI', title: 'Thức uống & Đồ giải khát', description: 'Từ vựng các loại nước giải khát, trà, cà phê và đồ uống có cồn.', category: 'food_dining', icon: 'Coffee', color: 'from-amber-600 to-yellow-700', is_custom: false, is_public: true, created_at: now, updated_at: now },
  { id: 'deck-seafood', user_id: 'user-teacher-1', author_name: 'VocaFast AI', title: 'Hải sản tươi sống', description: 'Các loại tôm, cua, cá, sò, hến và thủy hải sản biển.', category: 'food_dining', icon: 'Fish', color: 'from-cyan-500 to-blue-600', is_custom: false, is_public: true, created_at: now, updated_at: now },
  { id: 'deck-clothes', user_id: 'user-teacher-1', author_name: 'VocaFast AI', title: 'Quần áo & Trang phục', description: 'Trang phục thường ngày, phụ kiện thời trang và đồng phục.', category: 'daily_shopping', icon: 'Shirt', color: 'from-blue-500 to-indigo-600', is_custom: false, is_public: true, created_at: now, updated_at: now },
  { id: 'deck-colors', user_id: 'user-teacher-1', author_name: 'VocaFast AI', title: 'Màu sắc cơ bản & Pha màu', description: 'Bảng màu sắc phong phú từ cơ bản đến Gam màu ngọc bích.', category: 'daily_shopping', icon: 'Palette', color: 'from-violet-500 to-purple-600', is_custom: false, is_public: true, created_at: now, updated_at: now },
  { id: 'deck-fashion', user_id: 'user-teacher-1', author_name: 'VocaFast AI', title: 'Thời trang & Xu hướng', description: 'Từ vựng mốt thời trang, phong cách mặc và phụ kiện thời thượng.', category: 'daily_shopping', icon: 'Sparkles', color: 'from-pink-500 to-fuchsia-600', is_custom: false, is_public: true, created_at: now, updated_at: now },
  { id: 'deck-shops', user_id: 'user-teacher-1', author_name: 'VocaFast AI', title: 'Cửa hàng & Siêu thị', description: 'Địa điểm mua sắm, siêu thị, tiệm tạp hóa và dịch vụ bán lẻ.', category: 'daily_shopping', icon: 'ShoppingBag', color: 'from-teal-500 to-emerald-600', is_custom: false, is_public: true, created_at: now, updated_at: now },
  { id: 'deck-routines', user_id: 'user-teacher-1', author_name: 'VocaFast AI', title: 'Hoạt động hàng ngày', description: 'Lịch trình sinh hoạt, thói quen vệ sinh và công việc nhà.', category: 'daily_shopping', icon: 'Clock', color: 'from-sky-500 to-blue-600', is_custom: false, is_public: true, created_at: now, updated_at: now },
  { id: 'deck-numbers', user_id: 'user-teacher-1', author_name: 'VocaFast AI', title: 'Số đếm & Số thứ tự', description: 'Số đếm, số thứ tự, phân số và phép tính toán căn bản.', category: 'daily_shopping', icon: 'Hash', color: 'from-indigo-500 to-cyan-600', is_custom: false, is_public: true, created_at: now, updated_at: now },
  { id: 'deck-shopping', user_id: 'user-teacher-1', author_name: 'VocaFast AI', title: 'Mua sắm & Trả giá', description: 'Mẫu câu và từ vựng thanh toán, giảm giá, đổi trả hàng hóa.', category: 'daily_shopping', icon: 'ShoppingCart', color: 'from-emerald-500 to-teal-600', is_custom: false, is_public: true, created_at: now, updated_at: now },
  { id: 'deck-weather', user_id: 'user-teacher-1', author_name: 'VocaFast AI', title: 'Thời tiết & Khí hậu', description: 'Các hiện tượng thời tiết, nhiệt độ và dự báo khí hậu.', category: 'nature_environment', icon: 'Sun', color: 'from-sky-400 to-blue-600', is_custom: false, is_public: true, created_at: now, updated_at: now },
  { id: 'deck-environment', user_id: 'user-teacher-1', author_name: 'VocaFast AI', title: 'Môi trường & Hệ sinh thái', description: 'Ô nhiễm, biến đổi khí hậu, sinh thái và bảo vệ hành tinh.', category: 'nature_environment', icon: 'Globe', color: 'from-emerald-600 to-teal-700', is_custom: false, is_public: true, created_at: now, updated_at: now },
  { id: 'deck-animals', user_id: 'user-teacher-1', author_name: 'VocaFast AI', title: 'Con vật & Thế giới Động vật', description: 'Động vật nuôi, thú hoang dã, loài bò sát và chim chóc.', category: 'nature_environment', icon: 'Dog', color: 'from-amber-600 to-orange-700', is_custom: false, is_public: true, created_at: now, updated_at: now },
  { id: 'deck-insects', user_id: 'user-teacher-1', author_name: 'VocaFast AI', title: 'Côn trùng & Loài sâu bọ', description: 'Chuồn chuồn, bướm, ong, kiến và thế giới vi sinh vật.', category: 'nature_environment', icon: 'Bug', color: 'from-lime-500 to-green-600', is_custom: false, is_public: true, created_at: now, updated_at: now },
  { id: 'deck-flowers', user_id: 'user-teacher-1', author_name: 'VocaFast AI', title: 'Các loài hoa & Cây cảnh', description: 'Hoa hồng, hoa lan, hướng dương và các loại cây cỏ hoa lá.', category: 'nature_environment', icon: 'Flower2', color: 'from-pink-500 to-rose-500', is_custom: false, is_public: true, created_at: now, updated_at: now },
  { id: 'deck-school', user_id: 'user-teacher-1', author_name: 'VocaFast AI', title: 'Trường học & Giáo dục', description: 'Từ vựng trường lớp, môn học, giáo trình và thi cử.', category: 'education_career', icon: 'GraduationCap', color: 'from-blue-600 to-indigo-700', is_custom: false, is_public: true, created_at: now, updated_at: now },
  { id: 'deck-occupations', user_id: 'user-teacher-1', author_name: 'VocaFast AI', title: 'Nghề nghiệp & Nghề trong xã hội', description: 'Bác sĩ, kỹ sư, giáo viên, luật sư, doanh nhân và ngành nghề.', category: 'education_career', icon: 'Briefcase', color: 'from-indigo-600 to-purple-700', is_custom: false, is_public: true, created_at: now, updated_at: now },
  { id: 'deck-work', user_id: 'user-teacher-1', author_name: 'VocaFast AI', title: 'Công việc & Văn phòng', description: 'Deadline, họp hành, báo cáo, đồng nghiệp và công sở.', category: 'education_career', icon: 'Building2', color: 'from-slate-600 to-slate-800', is_custom: false, is_public: true, created_at: now, updated_at: now },
  { id: 'deck-military', user_id: 'user-teacher-1', author_name: 'VocaFast AI', title: 'Quân đội & An ninh', description: 'Quân ngũ, lực lượng vũ trang, cấp bậc và trang bị an ninh.', category: 'education_career', icon: 'Shield', color: 'from-stone-600 to-neutral-800', is_custom: false, is_public: true, created_at: now, updated_at: now },
  { id: 'deck-supplies', user_id: 'user-teacher-1', author_name: 'VocaFast AI', title: 'Đồ dùng học tập & Văn phòng phẩm', description: 'Bút, thước, cặp sách, máy tính và đồ dùng bàn học.', category: 'education_career', icon: 'PenTool', color: 'from-cyan-600 to-blue-700', is_custom: false, is_public: true, created_at: now, updated_at: now },
  { id: 'deck-travel', user_id: 'user-teacher-1', author_name: 'VocaFast AI', title: 'Du lịch & Khám phá', description: 'Sân bay, khách sạn, lịch trình chuyến đi và trải nghiệm du lịch.', category: 'places_services', icon: 'Plane', color: 'from-teal-500 to-cyan-600', is_custom: false, is_public: true, created_at: now, updated_at: now },
  { id: 'deck-traffic', user_id: 'user-teacher-1', author_name: 'VocaFast AI', title: 'Giao thông & Phương tiện', description: 'Xe cộ, biển báo, luật giao thông và đường sá đô thị.', category: 'places_services', icon: 'Car', color: 'from-blue-500 to-indigo-600', is_custom: false, is_public: true, created_at: now, updated_at: now },
  { id: 'deck-countries', user_id: 'user-teacher-1', author_name: 'VocaFast AI', title: 'Quốc gia & Quốc tịch', description: 'Tên các quốc gia, thủ đô, quốc tịch và văn hóa thế giới.', category: 'places_services', icon: 'Flag', color: 'from-red-500 to-amber-600', is_custom: false, is_public: true, created_at: now, updated_at: now },
  { id: 'deck-hometown', user_id: 'user-teacher-1', author_name: 'VocaFast AI', title: 'Quê hương & Làng quê', description: 'Từ vựng miêu tả quê hương, vùng nông thôn và cảnh vật làng quê.', category: 'places_services', icon: 'Home', color: 'from-green-600 to-emerald-700', is_custom: false, is_public: true, created_at: now, updated_at: now },
  { id: 'deck-hospital', user_id: 'user-teacher-1', author_name: 'VocaFast AI', title: 'Bệnh viện & Y tế', description: 'Phòng khám, y bác sĩ, đơn thuốc và điều trị bệnh.', category: 'places_services', icon: 'Stethoscope', color: 'from-rose-600 to-red-700', is_custom: false, is_public: true, created_at: now, updated_at: now },
  { id: 'deck-health', user_id: 'user-teacher-1', author_name: 'VocaFast AI', title: 'Sức khỏe & Chăm sóc cơ thể', description: 'Rèn luyện sức khỏe, triệu chứng bệnh và dinh dưỡng lành mạnh.', category: 'places_services', icon: 'Activity', color: 'from-emerald-500 to-green-600', is_custom: false, is_public: true, created_at: now, updated_at: now },
  { id: 'deck-postoffice', user_id: 'user-teacher-1', author_name: 'VocaFast AI', title: 'Bưu điện & Chuyển phát', description: 'Gửi thư, kiện hàng, bưu phẩm và dịch vụ logistics.', category: 'places_services', icon: 'Mail', color: 'from-amber-500 to-orange-600', is_custom: false, is_public: true, created_at: now, updated_at: now },
  { id: 'deck-banking', user_id: 'user-teacher-1', author_name: 'VocaFast AI', title: 'Ngân hàng & Tài chính', description: 'Giao dịch ngân hàng, thẻ ATM, tín dụng và chuyển tiền.', category: 'places_services', icon: 'Landmark', color: 'from-blue-700 to-indigo-900', is_custom: false, is_public: true, created_at: now, updated_at: now },
  { id: 'deck-sports', user_id: 'user-teacher-1', author_name: 'VocaFast AI', title: 'Các môn Thể thao', description: 'Bóng rổ, cầu lông, bơi lội, điền kinh và thi đấu thể thao.', category: 'leisure_festivals', icon: 'Trophy', color: 'from-amber-500 to-yellow-600', is_custom: false, is_public: true, created_at: now, updated_at: now },
  { id: 'deck-football', user_id: 'user-teacher-1', author_name: 'VocaFast AI', title: 'Bóng đá & Giải vô địch', description: 'Sân bóng, trọng tài, bàn thắng, cầu thủ và các giải đấu.', category: 'leisure_festivals', icon: 'Goal', color: 'from-emerald-500 to-green-600', is_custom: false, is_public: true, created_at: now, updated_at: now },
  { id: 'deck-movies', user_id: 'user-teacher-1', author_name: 'VocaFast AI', title: 'Phim ảnh & Điện ảnh', description: 'Rạp chiếu phim, đạo diễn, diễn viên và phim bom tấn.', category: 'leisure_festivals', icon: 'Film', color: 'from-purple-600 to-indigo-700', is_custom: false, is_public: true, created_at: now, updated_at: now },
  { id: 'deck-christmas', user_id: 'user-teacher-1', author_name: 'VocaFast AI', title: 'Giáng sinh & Đón Năm Mới', description: 'Cây thông, quà tặng, rồng rực rỡ và không khí Noel.', category: 'leisure_festivals', icon: 'Snowflake', color: 'from-red-600 to-emerald-700', is_custom: false, is_public: true, created_at: now, updated_at: now },
  { id: 'deck-midautumn', user_id: 'user-teacher-1', author_name: 'VocaFast AI', title: 'Tết Trung Thu', description: 'Bánh trung thu, lồng đèn, múa lân và đêm rằm tháng tám.', category: 'leisure_festivals', icon: 'Moon', color: 'from-amber-400 to-orange-500', is_custom: false, is_public: true, created_at: now, updated_at: now },
  { id: 'deck-tet', user_id: 'user-teacher-1', author_name: 'VocaFast AI', title: 'Tết Nguyên Đán', description: 'Hoa mai, hoa đào, bánh chưng, bao lì xì và đoàn tụ gia đình.', category: 'leisure_festivals', icon: 'Gift', color: 'from-red-600 to-amber-500', is_custom: false, is_public: true, created_at: now, updated_at: now }
];

const CARDS_TO_SEED = [
  { id: 'card-cat-1-1', deck_id: 'deck-family', user_id: 'user-teacher-1', word: 'Ancestor', ipa: '/ˈæn.ses.tər/', part_of_speech: 'noun', meaning: 'Tổ tiên, ông bà cụ kị', example_en: 'My ancestors came to America from Ireland in the 19th century.', example_vi: 'Tổ tiên của tôi đã đến Mỹ từ Ireland vào thế kỷ 19.', mnemonic: 'An-ces-tor -> Ơn cha ông tổ tiên.', srs_level: 0, interval_days: 0, ease_factor: 2.5, repetition_count: 0, due_date: today, mastery: 'new', created_at: now },
  { id: 'card-cat-1-2', deck_id: 'deck-family', user_id: 'user-teacher-1', word: 'Sibling', ipa: '/ˈsɪb.lɪŋ/', part_of_speech: 'noun', meaning: 'Anh chị em ruột', example_en: 'I have two siblings: an older brother and a younger sister.', example_vi: 'Tôi có hai anh chị em ruột: một anh trai và một em gái.', mnemonic: 'Sib-ling -> Xít lại gần anh chị em.', srs_level: 0, interval_days: 0, ease_factor: 2.5, repetition_count: 0, due_date: today, mastery: 'new', created_at: now },
  { id: 'card-cat-1-3', deck_id: 'deck-family', user_id: 'user-teacher-1', word: 'Relative', ipa: '/ˈrel.ə.tɪv/', part_of_speech: 'noun', meaning: 'Họ hàng, người thân', example_en: 'All our relatives came together for the family reunion.', example_vi: 'Tất cả họ hàng của chúng tôi đã tụ họp cho buổi đoàn tụ gia đình.', mnemonic: 'Re-lative -> Rẻ cho người thân.', srs_level: 0, interval_days: 0, ease_factor: 2.5, repetition_count: 0, due_date: today, mastery: 'new', created_at: now },
  { id: 'card-cat-2-1', deck_id: 'deck-personality', user_id: 'user-teacher-1', word: 'Optimistic', ipa: '/ˌɒp.tɪˈmɪs.tɪk/', part_of_speech: 'adjective', meaning: 'Lạc quan, yêu đời', example_en: 'She is optimistic about her chances of winning the competition.', example_vi: 'Cô ấy rất lạc quan về cơ hội chiến thắng cuộc thi của mình.', mnemonic: 'Op-ti-mistic -> Ốp tim yêu đời lạc quan.', srs_level: 0, interval_days: 0, ease_factor: 2.5, repetition_count: 0, due_date: today, mastery: 'new', created_at: now },
  { id: 'card-cat-2-2', deck_id: 'deck-personality', user_id: 'user-teacher-1', word: 'Compassionate', ipa: '/kəmˈpæʃ.ən.ət/', part_of_speech: 'adjective', meaning: 'Giàu lòng nhân ái, giàu tình thương', example_en: 'Nurses are usually very compassionate towards their patients.', example_vi: 'Y tá thường rất giàu lòng nhân ái đối với các bệnh nhân của mình.', mnemonic: 'Compassion -> Tình thương nhân ái.', srs_level: 0, interval_days: 0, ease_factor: 2.5, repetition_count: 0, due_date: today, mastery: 'new', created_at: now },
  { id: 'card-cat-3-1', deck_id: 'deck-emotions', user_id: 'user-teacher-1', word: 'Anxious', ipa: '/ˈæŋk.ʃəs/', part_of_speech: 'adjective', meaning: 'Lo âu, bồn chồn', example_en: 'He felt anxious about the upcoming job interview.', example_vi: 'Anh ấy cảm thấy lo âu về buổi phỏng vấn xin việc sắp tới.', mnemonic: 'An-xious -> Ăn không ngon vì lo âu.', srs_level: 0, interval_days: 0, ease_factor: 2.5, repetition_count: 0, due_date: today, mastery: 'new', created_at: now },
  { id: 'card-cat-3-2', deck_id: 'deck-emotions', user_id: 'user-teacher-1', word: 'Enthusiastic', ipa: '/ɪnˌθjuː.ziˈæs.tɪk/', part_of_speech: 'adjective', meaning: 'Hào hứng, nhiệt tình', example_en: 'The audience was very enthusiastic about the performance.', example_vi: 'Khán giả đã rất hào hứng với phần trình diễn.', mnemonic: 'En-thu-siastic -> Hào hứng nhiệt tình.', srs_level: 0, interval_days: 0, ease_factor: 2.5, repetition_count: 0, due_date: today, mastery: 'new', created_at: now },
  { id: 'card-cat-4-1', deck_id: 'deck-describing-people', user_id: 'user-teacher-1', word: 'Gorgeous', ipa: '/ˈɡɔː.dʒəs/', part_of_speech: 'adjective', meaning: 'Lộng lẫy, cực kỳ xinh đẹp', example_en: 'She looked absolutely gorgeous in her wedding dress.', example_vi: 'Cô ấy trông tuyệt đẹp lộng lẫy trong chiếc váy cưới.', mnemonic: 'Gor-geous -> Gợi cảm xinh đẹp lộng lẫy.', srs_level: 0, interval_days: 0, ease_factor: 2.5, repetition_count: 0, due_date: today, mastery: 'new', created_at: now },
  { id: 'card-cat-4-2', deck_id: 'deck-describing-people', user_id: 'user-teacher-1', word: 'Slender', ipa: '/ˈslen.dər/', part_of_speech: 'adjective', meaning: 'Thon thả, mảnh mai', example_en: 'The dancer had a long and slender neck.', example_vi: 'Vũ công có một chiếc cổ dài và thon thả.', mnemonic: 'Slen-der -> Thon thả mảnh mai.', srs_level: 0, interval_days: 0, ease_factor: 2.5, repetition_count: 0, due_date: today, mastery: 'new', created_at: now },
  { id: 'card-cat-5-1', deck_id: 'deck-body-actions', user_id: 'user-teacher-1', word: 'Stretch', ipa: '/stretʃ/', part_of_speech: 'verb', meaning: 'Vươn vai, duỗi người', example_en: 'Always stretch your muscles before exercising.', example_vi: 'Luôn vươn duỗi cơ bắp trước khi tập thể dục.', mnemonic: 'Stretch -> Sút cơ vươn vai.', srs_level: 0, interval_days: 0, ease_factor: 2.5, repetition_count: 0, due_date: today, mastery: 'new', created_at: now },
  { id: 'card-cat-6-1', deck_id: 'deck-vegetables', user_id: 'user-teacher-1', word: 'Broccoli', ipa: '/ˈbrɒk.əl.i/', part_of_speech: 'noun', meaning: 'Bông cải xanh, súp lơ xanh', example_en: 'Broccoli is rich in vitamins and fiber.', example_vi: 'Súp lơ xanh rất giàu vitamin và chất xơ.', mnemonic: 'Bông cải xanh súp lơ.', srs_level: 0, interval_days: 0, ease_factor: 2.5, repetition_count: 0, due_date: today, mastery: 'new', created_at: now },
  { id: 'card-cat-6-2', deck_id: 'deck-vegetables', user_id: 'user-teacher-1', word: 'Spinach', ipa: '/ˈspɪn.ɪtʃ/', part_of_speech: 'noun', meaning: 'Rau bina, rau chân vịt', example_en: 'Spinach salad is healthy and delicious.', example_vi: 'Salad rau chân vịt rất lành mạnh và ngon miệng.', mnemonic: 'Rau chân vịt Popeye.', srs_level: 0, interval_days: 0, ease_factor: 2.5, repetition_count: 0, due_date: today, mastery: 'new', created_at: now },
  { id: 'card-cat-7-1', deck_id: 'deck-food-dishes', user_id: 'user-teacher-1', word: 'Delicacy', ipa: '/ˈdel.ɪ.kə.si/', part_of_speech: 'noun', meaning: 'Món ăn cao lương mỹ vị, đặc sản', example_en: 'Caviar is considered a luxury delicacy around the world.', example_vi: 'Trứng cá tầm được coi là món cao lương mỹ vị sang trọng trên toàn thế giới.', mnemonic: 'De-licacy -> Đã miệng cao lương mỹ vị.', srs_level: 0, interval_days: 0, ease_factor: 2.5, repetition_count: 0, due_date: today, mastery: 'new', created_at: now },
  { id: 'card-cat-7-2', deck_id: 'deck-food-dishes', user_id: 'user-teacher-1', word: 'Appetizer', ipa: '/ˈæp.ə.taɪ.zər/', part_of_speech: 'noun', meaning: 'Món khai vị', example_en: 'We ordered spring rolls as an appetizer before main course.', example_vi: 'Chúng tôi đã gọi nem rán làm món khai vị trước món chính.', mnemonic: 'App-etite -> Kích thích thèm ăn.', srs_level: 0, interval_days: 0, ease_factor: 2.5, repetition_count: 0, due_date: today, mastery: 'new', created_at: now },
  { id: 'card-cat-8-1', deck_id: 'deck-fruits', user_id: 'user-teacher-1', word: 'Pomegranate', ipa: '/ˈpɒm.ɪ.ɡræn.ɪt/', part_of_speech: 'noun', meaning: 'Quả lựu', example_en: 'Pomegranate seeds add a sweet taste to salads.', example_vi: 'Hạt lựu thêm vị ngọt ngào cho món salad.', mnemonic: 'Quả lựu mọng nước.', srs_level: 0, interval_days: 0, ease_factor: 2.5, repetition_count: 0, due_date: today, mastery: 'new', created_at: now },
  { id: 'card-cat-9-1', deck_id: 'deck-kitchenware', user_id: 'user-teacher-1', word: 'Spatula', ipa: '/ˈspætʃ.ə.lə/', part_of_speech: 'noun', meaning: 'Dụng cụ lật thức ăn, xẻng nấu ăn', example_en: 'Use a silicone spatula to flip the pancakes gently.', example_vi: 'Dùng xẻng nấu ăn bằng silicone để lật bánh kếp nhẹ nhàng.', mnemonic: 'Xẻng lật chiên trứng.', srs_level: 0, interval_days: 0, ease_factor: 2.5, repetition_count: 0, due_date: today, mastery: 'new', created_at: now },
  { id: 'card-cat-10-1', deck_id: 'deck-beverages', user_id: 'user-teacher-1', word: 'Beverage', ipa: '/ˈbev.ər.ɪdʒ/', part_of_speech: 'noun', meaning: 'Đồ uống, thức uống', example_en: 'Alcoholic beverages are not served to minors.', example_vi: 'Đồ uống có cồn không được phục vụ cho người chưa thành niên.', mnemonic: 'Beverage -> Đồ uống.', srs_level: 0, interval_days: 0, ease_factor: 2.5, repetition_count: 0, due_date: today, mastery: 'new', created_at: now },
  { id: 'card-cat-11-1', deck_id: 'deck-seafood', user_id: 'user-teacher-1', word: 'Lobster', ipa: '/ˈlɒb.stər/', part_of_speech: 'noun', meaning: 'Tôm hùm', example_en: 'Grilled lobster with garlic butter is a popular coastal dish.', example_vi: 'Tôm hùm nướng bơ tỏi là món ăn vùng biển rất được ưa chuộng.', mnemonic: 'Lobster -> Tôm hùm bơ tỏi.', srs_level: 0, interval_days: 0, ease_factor: 2.5, repetition_count: 0, due_date: today, mastery: 'new', created_at: now },
  { id: 'card-cat-12-1', deck_id: 'deck-clothes', user_id: 'user-teacher-1', word: 'Apparel', ipa: '/əˈpær.əl/', part_of_speech: 'noun', meaning: 'Trang phục, quần áo', example_en: 'The store sells high-end sports apparel for athletes.', example_vi: 'Cửa hàng bán trang phục thể thao cao cấp cho các vận động viên.', mnemonic: 'Apparel -> Trang phục quần áo.', srs_level: 0, interval_days: 0, ease_factor: 2.5, repetition_count: 0, due_date: today, mastery: 'new', created_at: now },
  { id: 'card-cat-13-1', deck_id: 'deck-colors', user_id: 'user-teacher-1', word: 'Turquoise', ipa: '/ˈtɜː.kwɔɪz/', part_of_speech: 'noun', meaning: 'Màu xanh ngọc bích', example_en: 'The tropical ocean was a stunning shade of turquoise.', example_vi: 'Biển nhiệt đới có màu xanh ngọc bích tuyệt đẹp.', mnemonic: 'Xanh ngọc bích.', srs_level: 0, interval_days: 0, ease_factor: 2.5, repetition_count: 0, due_date: today, mastery: 'new', created_at: now },
  { id: 'card-cat-14-1', deck_id: 'deck-fashion', user_id: 'user-teacher-1', word: 'Trendy', ipa: '/ˈtren.di/', part_of_speech: 'adjective', meaning: 'Hợp thời trang, chạy theo mốt', example_en: 'She loves wearing trendy clothes to social events.', example_vi: 'Cô ấy thích mặc quần áo hợp thời trang đến các sự kiện xã hội.', mnemonic: 'Trend -> Hợp mốt thời trang.', srs_level: 0, interval_days: 0, ease_factor: 2.5, repetition_count: 0, due_date: today, mastery: 'new', created_at: now },
  { id: 'card-cat-15-1', deck_id: 'deck-shops', user_id: 'user-teacher-1', word: 'Discount', ipa: '/ˈdɪs.kaʊnt/', part_of_speech: 'noun', meaning: 'Sự giảm giá, chiết khấu', example_en: 'Students receive a 20% discount on movie tickets.', example_vi: 'Học sinh được giảm giá 20% khi mua vé xem phim.', mnemonic: 'Discount -> Giảm giá chiết khấu.', srs_level: 0, interval_days: 0, ease_factor: 2.5, repetition_count: 0, due_date: today, mastery: 'new', created_at: now },
  { id: 'card-cat-16-1', deck_id: 'deck-routines', user_id: 'user-teacher-1', word: 'Routine', ipa: '/ruːˈtiːn/', part_of_speech: 'noun', meaning: 'Thói quen hàng ngày, lịch trình', example_en: 'Exercise has become part of my daily routine.', example_vi: 'Tập thể dục đã trở thành một phần trong thói quen hàng ngày của tôi.', mnemonic: 'Routine -> Thói quen sinh hoạt.', srs_level: 0, interval_days: 0, ease_factor: 2.5, repetition_count: 0, due_date: today, mastery: 'new', created_at: now },
  { id: 'card-cat-17-1', deck_id: 'deck-shopping', user_id: 'user-teacher-1', word: 'Bargain', ipa: '/ˈbɑː.ɡɪn/', part_of_speech: 'noun', meaning: 'Món hời, giá rẻ', example_en: 'This jacket was a real bargain at half price.', example_vi: 'Chiếc áo khoác này thực sự là một món hời với giá nửa tiền.', mnemonic: 'Bargain -> Trả giá món hời.', srs_level: 0, interval_days: 0, ease_factor: 2.5, repetition_count: 0, due_date: today, mastery: 'new', created_at: now },
  { id: 'card-cat-18-1', deck_id: 'deck-weather', user_id: 'user-teacher-1', word: 'Forecast', ipa: '/ˈfɔː.kɑːst/', part_of_speech: 'noun', meaning: 'Dự báo thời tiết', example_en: 'The weather forecast predicts heavy rain tomorrow.', example_vi: 'Dự báo thời tiết dự đoán sẽ có mưa lớn vào ngày mai.', mnemonic: 'Forecast -> Dự báo trước.', srs_level: 0, interval_days: 0, ease_factor: 2.5, repetition_count: 0, due_date: today, mastery: 'new', created_at: now },
  { id: 'card-cat-19-1', deck_id: 'deck-environment', user_id: 'user-teacher-1', word: 'Ecosystem', ipa: '/ˈiː.kəʊˌsɪs.təm/', part_of_speech: 'noun', meaning: 'Hệ sinh thái', example_en: 'Pollution threatens the fragile marine ecosystem.', example_vi: 'Ô nhiễm đe dọa hệ sinh thái biển mỏng manh.', mnemonic: 'Eco-system -> Hệ sinh thái.', srs_level: 0, interval_days: 0, ease_factor: 2.5, repetition_count: 0, due_date: today, mastery: 'new', created_at: now },
  { id: 'card-cat-20-1', deck_id: 'deck-animals', user_id: 'user-teacher-1', word: 'Chameleon', ipa: '/kəˈmiː.li.ən/', part_of_speech: 'noun', meaning: 'Tắc kè hoa', example_en: 'The chameleon changes its skin color to blend into trees.', example_vi: 'Tắc kè hoa đổi màu da để hòa lẫn vào cây cối.', mnemonic: 'Chameleon -> Tắc kè hoa đổi màu.', srs_level: 0, interval_days: 0, ease_factor: 2.5, repetition_count: 0, due_date: today, mastery: 'new', created_at: now },
  { id: 'card-cat-21-1', deck_id: 'deck-insects', user_id: 'user-teacher-1', word: 'Dragonfly', ipa: '/ˈdræɡ.ən.flaɪ/', part_of_speech: 'noun', meaning: 'Con chuồn chuồn', example_en: 'Dragonflies hovered gracefully over the quiet pond.', example_vi: 'Những con chuồn chuồn chao lượn duyên dáng trên mặt hồ yên ả.', mnemonic: 'Dragonfly -> Chuồn chuồn bay thấp.', srs_level: 0, interval_days: 0, ease_factor: 2.5, repetition_count: 0, due_date: today, mastery: 'new', created_at: now },
  { id: 'card-cat-22-1', deck_id: 'deck-flowers', user_id: 'user-teacher-1', word: 'Orchid', ipa: '/ˈɔː.kɪd/', part_of_speech: 'noun', meaning: 'Hoa phong lan', example_en: 'She cultivates rare orchids in her greenhouse.', example_vi: 'Cô ấy trồng những loài hoa lan quý hiếm trong nhà kính của mình.', mnemonic: 'Orchid -> Hoa lan quý.', srs_level: 0, interval_days: 0, ease_factor: 2.5, repetition_count: 0, due_date: today, mastery: 'new', created_at: now },
  { id: 'card-cat-23-1', deck_id: 'deck-school', user_id: 'user-teacher-1', word: 'Curriculum', ipa: '/kəˈrɪk.jə.ləm/', part_of_speech: 'noun', meaning: 'Chương trình giảng dạy, giáo trình', example_en: 'The school updated its science curriculum this year.', example_vi: 'Trường học đã cập nhật chương trình giảng dạy môn khoa học trong năm nay.', mnemonic: 'Curriculum -> Khung chương trình học.', srs_level: 0, interval_days: 0, ease_factor: 2.5, repetition_count: 0, due_date: today, mastery: 'new', created_at: now },
  { id: 'card-cat-24-1', deck_id: 'deck-occupations', user_id: 'user-teacher-1', word: 'Entrepreneur', ipa: '/ˌɒn.trə.prəˈnɜːr/', part_of_speech: 'noun', meaning: 'Nhà khởi nghiệp, doanh nhân', example_en: 'The young entrepreneur launched a successful tech startup.', example_vi: 'Nhà khởi nghiệp trẻ đã ra mắt một công ty công nghệ thành công.', mnemonic: 'Entrepreneur -> Nhà khởi nghiệp.', srs_level: 0, interval_days: 0, ease_factor: 2.5, repetition_count: 0, due_date: today, mastery: 'new', created_at: now },
  { id: 'card-cat-25-1', deck_id: 'deck-work', user_id: 'user-teacher-1', word: 'Deadline', ipa: '/ˈded.laɪn/', part_of_speech: 'noun', meaning: 'Thời hạn hoàn thành công việc', example_en: 'We must work overtime to meet the project deadline.', example_vi: 'Chúng ta phải làm thêm giờ để kịp thời hạn dự án.', mnemonic: 'Deadline -> Hạn chót công việc.', srs_level: 0, interval_days: 0, ease_factor: 2.5, repetition_count: 0, due_date: today, mastery: 'new', created_at: now },
  { id: 'card-cat-26-1', deck_id: 'deck-travel', user_id: 'user-teacher-1', word: 'Itinerary', ipa: '/aɪˈtɪn.ər.ər.i/', part_of_speech: 'noun', meaning: 'Lịch trình chuyến đi', example_en: 'Our travel itinerary includes visits to ancient temples.', example_vi: 'Lịch trình du lịch của chúng tôi bao gồm việc thăm các ngôi đền cổ.', mnemonic: 'Itinerary -> Lịch trình du lịch.', srs_level: 0, interval_days: 0, ease_factor: 2.5, repetition_count: 0, due_date: today, mastery: 'new', created_at: now },
  { id: 'card-cat-27-1', deck_id: 'deck-traffic', user_id: 'user-teacher-1', word: 'Pedestrian', ipa: '/pəˈdes.tri.ən/', part_of_speech: 'noun', meaning: 'Người đi bộ', example_en: 'Drivers must yield to pedestrians at the zebra crossing.', example_vi: 'Tài xế phải nhường đường cho người đi bộ tại vạch sang đường.', mnemonic: 'Pedestrian -> Người đi bộ sang đường.', srs_level: 0, interval_days: 0, ease_factor: 2.5, repetition_count: 0, due_date: today, mastery: 'new', created_at: now },
  { id: 'card-cat-28-1', deck_id: 'deck-health', user_id: 'user-teacher-1', word: 'Symptom', ipa: '/ˈsɪmp.təm/', part_of_speech: 'noun', meaning: 'Triệu chứng bệnh', example_en: 'Fever and cough are common symptoms of the flu.', example_vi: 'Sốt và ho là các triệu chứng phổ biến của bệnh cúm.', mnemonic: 'Symptom -> Triệu chứng bệnh.', srs_level: 0, interval_days: 0, ease_factor: 2.5, repetition_count: 0, due_date: today, mastery: 'new', created_at: now },
  { id: 'card-cat-29-1', deck_id: 'deck-banking', user_id: 'user-teacher-1', word: 'Transaction', ipa: '/trænˈzæk.ʃən/', part_of_speech: 'noun', meaning: 'Giao dịch tài chính, ngân hàng', example_en: 'You will receive a confirmation message for every transaction.', example_vi: 'Bạn sẽ nhận được tin nhắn xác nhận cho mỗi giao dịch.', mnemonic: 'Transaction -> Giao dịch ngân hàng.', srs_level: 0, interval_days: 0, ease_factor: 2.5, repetition_count: 0, due_date: today, mastery: 'new', created_at: now },
  { id: 'card-cat-30-1', deck_id: 'deck-football', user_id: 'user-teacher-1', word: 'Championship', ipa: '/ˈtʃæm.pi.ən.ʃɪp/', part_of_speech: 'noun', meaning: 'Giải vô địch, chức vô địch', example_en: 'The team celebrated winning the national soccer championship.', example_vi: 'Đội bóng đã ăn mừng chiến thắng giải vô địch bóng đá quốc gia.', mnemonic: 'Champion -> Giải vô địch bóng đá.', srs_level: 0, interval_days: 0, ease_factor: 2.5, repetition_count: 0, due_date: today, mastery: 'new', created_at: now },
  { id: 'card-cat-31-1', deck_id: 'deck-movies', user_id: 'user-teacher-1', word: 'Blockbuster', ipa: '/ˈblɒkˌbʌs.tər/', part_of_speech: 'noun', meaning: 'Phim bom tấn', example_en: 'The new superhero movie broke box office records as a summer blockbuster.', example_vi: 'Bộ phim siêu nhân mới đã phá kỷ lục doanh thu phòng vé với tư cách là phim bom tấn mùa hè.', mnemonic: 'Blockbuster -> Phim bom tấn phòng vé.', srs_level: 0, interval_days: 0, ease_factor: 2.5, repetition_count: 0, due_date: today, mastery: 'new', created_at: now },
  { id: 'card-cat-32-1', deck_id: 'deck-tet', user_id: 'user-teacher-1', word: 'Festival', ipa: '/ˈfes.tɪ.vəl/', part_of_speech: 'noun', meaning: 'Lễ hội, ngày hội', example_en: 'The Mid-Autumn Festival is celebrated with lanterns and mooncakes.', example_vi: 'Tết Trung Thu được ăn mừng với lồng đèn và bánh trung thu.', mnemonic: 'Festival -> Ngày hội lễ hội.', srs_level: 0, interval_days: 0, ease_factor: 2.5, repetition_count: 0, due_date: today, mastery: 'new', created_at: now }
];

async function seed() {
  console.log('🌱 Seeding 42 Category Decks into Supabase...');
  const { error: deckError } = await supabase.from('decks').upsert(DECKS_TO_SEED, { onConflict: 'id' });
  if (deckError) {
    console.error('❌ Error seeding Decks:', deckError);
  } else {
    console.log('✅ Successfully seeded 42 Decks into Supabase!');
  }

  console.log('\n🎴 Seeding Cards into Supabase...');
  const { error: cardError } = await supabase.from('cards').upsert(CARDS_TO_SEED, { onConflict: 'id' });
  if (cardError) {
    console.error('❌ Error seeding Cards:', cardError);
  } else {
    console.log(`✅ Successfully seeded ${CARDS_TO_SEED.length} Cards into Supabase!`);
  }

  const { count } = await supabase.from('cards').select('*', { count: 'exact', head: true });
  console.log(`\n🎉 Total cards currently in Supabase Database: ${count}`);
}

seed().catch(console.error);
